import Head from 'next/head'
import { Inter } from 'next/font/google'
import Hero from '@/components/Hero'
import News from '@/components/News'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>URANIA | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-stars bg-cover bg-center h-screen w-screen absolute z-0' />
      <Hero />
      <News />
    </>
  )
}
